version: '3'

services:

  db:
    image: redis:7.0.9-alpine3.17
    restart: unless-stopped
    volumes:
      - redis_data:/data

  server:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  redis_data: